### ISSUE TITLE
Default White List

### ISSUE THREAD

**Issue by relipe** [flaviostutz/dockerwall#1]
It would be interesting if we could create a list of IP addresses that we passed through the ".env" environment variable file so it would be ignored by Dockerwall. Ex. DNS server ip.

**Comment by flaviostutz** [comment]
Great feature!

**Comment by flaviostutz** [comment]
Please take a look if the new flag "default.outbound" of version 1.5.0 solves your problem

**Comment by relipe** [comment]
Very good. This solution got better than the order.
