### ISSUE TITLE
second HELP line for metric name "dockerwall_container_packets"

### ISSUE THREAD

**Issue by relipe** [flaviostutz/dockerwall#3]
After installing dockerwall, the metrics generated from the targets are duplicated as attached images.
![metrics](https://user-images.githubusercontent.com/33091987/62732244-43aec300-b9fa-11e9-82f5-e80f96bf2f1f.png)
![Screenshot_2019-08-08 Prometheus Time Series Collection and Processing Server](https://user-images.githubusercontent.com/33091987/62732262-52957580-b9fa-11e9-8af1-44ec211609fc.png)

**Comment by relipe** [comment]
I tested with the newer version of prometheus and it worked. Then I realized that the error only occurred with the old version of prometheus. Using dockerwall version 1.9.1.

**Comment by flaviostutz** [comment]
Please check if version 1.9.2 clears out your issues.

**Comment by relipe** [comment]
Version 1.9.2 has the same problem as version 1.9.1 compared to old version prometheus (0.19.1).
