### ISSUE TITLE
The DockerWall is not configuring all possible hosts' IPs

### ISSUE THREAD

**Issue by MichaelRSilva** [flaviostutz/dockerwall#5]
The following label has been added to the docker-compose.yml file:
`- "dockerwall.outbound=canalrural.uol.com.br"`

However, the DockerWall did not configure all IPs for hostname [https://canalrural.uol.com.br](https://canalrural.uol.com.br), the application (which was running in the Docker container) was unable to access all subpages because the hostname balancer directed access to multiple IPs.

It is possible evaluate all IPs representing this hostname by going to: [https://www.whatsmydns.net/#A/canalrural.uol.com.br](https://www.whatsmydns.net/#A/canalrural.uol.com.br).

The application was only able to access the full content after adding all the corresponding IPs, for example:
`- "dockerwall.outbound=canalrural.uol.com.br,187.18.60.228,187.18.60.229,200.98.2.150, 187.18.60.223,200.98.2.62,187.18.60.229,200.98.2.112,200.98.2.94,187.18.60.216"`.

**Comment by flaviostutz** [comment]
Hm... which command did you use to get all ips?

**Comment by flaviostutz** [comment]
@MichaelRSilva, regarding to the change of IPs among nslookup calls, Dockerwall would handle this kind of change and possibly would stop showing unnecessary drops according to the following after some hours:

ExecShellf("dig A +short %s | xargs -L1 ipset -A %s", domainsstr, ipsetName)

According to this, new IPs being returned by the "dig" command would get added to the list of authorized IPs, not replacing them, but this update is run only each 5 minutes. Could you verify this behavior?

If this is OK, what we could do is to forcebly trigger ipset update when any eventual dns query returns an IP that was not authorized before.

**Comment by MichaelRSilva** [comment]
@flaviostutz, I don't know if I understand your question. Have you made an adjustment to which the Dockerwall can block requests for a new IP (regarding a dns) for a maximum of 5 minutes?

Other question: If the new IP doesn't replace the old ip. Can't the white list grow so large that it causes a memory leak?

**Comment by flaviostutz** [comment]
The memory leak is indeed a possible problem, but regarding to the authorized IPs, the thing is: Dockerwall refreshes the IP list for a given DNS each 5 minutes, so currently it will possibly miss some IPs in your case (they will keep blocked) because your IPs are being refreshed at each minute.

**Comment by MichaelRSilva** [comment]
In this case, the command returns 1 IP at each execution, the number (X) of possible IPs for a DNS is finite. Let's exercise assuming that X = 10.

Dockerwall will take approximately 50 minutes (in the best case, the command will not necessarily return an ip other than the previous call) to add all 10 ips in the whitelist, meaning we may be losing information for 50 minutes.

For my case, this time would be acceptable, but for other cases it means a big loss. I will check if this behavior is occurring.

About your suggestion, I thought it was a great idea, we could forcibly trigger the ipset update when any eventual DNS query returns an unauthorized IP before.

**Comment by flaviostutz** [comment]
Please check if version 1.11.0 solves this problem.

**Comment by MichaelRSilva** [comment]
@flaviostutz I checked. This version solved the problem.
Thanks!
